<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-17T16:25:17 SAST" name="Default suite" finished-at="2023-10-17T16:25:18 SAST" duration-ms="1114">
    <groups>
    </groups>
    <test started-at="2023-10-17T16:25:17 SAST" name="Default test" finished-at="2023-10-17T16:25:18 SAST" duration-ms="1114">
      <class name="packOne.Demo1">
        <test-method signature="firstTestCase()[pri:0, instance:packOne.Demo1@6fd83fc1]" started-at="2023-10-17T16:25:17 SAST" name="firstTestCase" finished-at="2023-10-17T16:25:18 SAST" duration-ms="1040" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method packOne.Demo1.firstTestCase() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method packOne.Demo1.firstTestCase() didn't finish within the time-out 1000
at java.base@17.0.2/java.lang.Thread.sleep(Native Method)
at app//packOne.Demo1.firstTestCase(Demo1.java:12)
at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTestCase -->
        <test-method signature="secondTestCase()[pri:0, instance:packOne.Demo1@6fd83fc1]" started-at="2023-10-17T16:25:18 SAST" name="secondTestCase" finished-at="2023-10-17T16:25:18 SAST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTestCase -->
      </class> <!-- packOne.Demo1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
